apiVersion: v1
kind: Service
metadata:
  name: kafka-producer
spec:
  type: {{ .Values.kafkaProducer.service.type }}
  ports:
    - port: {{ .Values.kafkaProducer.service.port }}
      targetPort: 8080
  selector:
    app: kafka-producer
