apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: {{ .Values.kafkaConsumer.replicaCount }}
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: "{{ .Values.kafkaConsumer.image.repository }}:{{ .Values.kafkaConsumer.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: "{{ (index .Values.kafkaConsumer.env 0).value }}"
          resources:
            requests:
              cpu: {{ .Values.kafkaConsumer.resources.requests.cpu }}
              memory: {{ .Values.kafkaConsumer.resources.requests.memory }}
            limits:
              cpu: {{ .Values.kafkaConsumer.resources.limits.cpu }}
              memory: {{ .Values.kafkaConsumer.resources.limits.memory }}
