apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: {{ .Values.kafkaProducer.replicaCount }}
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: "{{ .Values.kafkaProducer.image.repository }}:{{ .Values.kafkaProducer.image.tag }}"
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER
              value: "{{ (index .Values.kafkaProducer.env 0).value }}"
          resources:
            requests:
              cpu: {{ .Values.kafkaProducer.resources.requests.cpu }}
              memory: {{ .Values.kafkaProducer.resources.requests.memory }}
            limits:
              cpu: {{ .Values.kafkaProducer.resources.limits.cpu }}
              memory: {{ .Values.kafkaProducer.resources.limits.memory }}
