apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer
spec:
  type: {{ .Values.kafkaConsumer.service.type }}
  ports:
    - port: {{ .Values.kafkaConsumer.service.port }}
      targetPort: 8080
  selector:
    app: kafka-consumer
